# The minimum & maximum amount of time a swap can happen.
# The delay is a randomly generated value between these two values. (in seconds)
min-delay: 5.0
max-delay: 45.0
#
# The message that's sent for every player that is swapped
# swap-format is replaced with %msg% that's defined in swap-message
# Only initialize one line for swap-format as '%msg%'
# Use '&' for color codes
# Chat Placeholders:
#   - '%original%' ~ The original player (Only works in swap-message)
#   - '%new%'      ~ The new player (Only works in swap-message)
#   - '&delay%'    ~ How long the swap took (Only works in swap-format)
#   - '%msg%'      ~ The individual swap message (Only works in swap-format)
swap-format: '&b%original% -> %new%'
swap-message:
  - '&e&l----------------------------'
  - '&aSwap took: %delay% seconds.'
  - '%msg%'
  - '&e&l----------------------------'
