main: com.playerswap.PlayerSwap
name: PlayerSwap
version: '1.0'
description: 'A simple player swapping plugin.'
author: 'nmahdi - https://github.com/nmahdi'
commands:
  playerswap:
    description: 'Primary admin command. Run /ps for more details.'
    aliases: ps
    permission: playerswap.admin